language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: nosetests
after_success:
  - bash <(curl -s https://codecov.io/bash)
